<a href="https://colab.research.google.com/github/umiSirya/FUTURE_DS_01/blob/main/sales_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
dp = pd.read_csv('/content/data.csv', encoding='latin1')
dp.head()
dp.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
75101,542541,22124,SET OF 2 TEA TOWELS PING MICROWAVE,1.0,1/28/2011 14:25,2.46,NaN,United Kingdom
75102,542541,22131,FOOD CONTAINER SET 3 LOVE HEART,1.0,1/28/2011 14:25,4.13,NaN,United Kingdom
75103,542541,22135,MINI LADLE LOVE HEART PINK,1.0,1/28/2011 14:25,0.83,NaN,United Kingdom
75104,542541,22148,EASTER CRAFT 4 CHICKS,3.0,1/28/2011 14:25,4.13,NaN,United Kingdom
75105,542541,22149,FELTCRAFT 6 FLOWER FRIENDS,NaN,NaN,NaN,NaN,NaN

# **EDA**

In [5]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75106 entries, 0 to 75105
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    75106 non-null  object
 1   StockCode    75106 non-null  object
 2   Description  74903 non-null  object
 3   Quantity     75105 non-null  float64
 4   InvoiceDate  75105 non-null  object
 5   UnitPrice    75105 non-null  float64
 6   CustomerID   46828 non-null  float64
 7   Country      75105 non-null  object
dtypes: float64(3), object(5)
memory usage: 4.6+ MB

In [6]:
#missing values
dp.isnull().sum()

InvoiceNo          0
StockCode          0
Description      203
Quantity           1
InvoiceDate        1
UnitPrice          1
CustomerID     28278
Country            1
dtype: int64

In [7]:
dp.describe()

           Quantity     UnitPrice    CustomerID
count  75105.000000  75105.000000  46828.000000
mean       8.438147      5.639838  15347.426283
std      387.156865    136.348094   1762.929568
min   -74215.000000      0.000000  12346.000000
25%        1.000000      1.250000  13959.000000
50%        2.000000      2.510000  15311.000000
75%        8.000000      4.210000  16931.000000
max    74215.000000  16888.020000  18283.000000

In [8]:
dp["InvoiceNo"].value_counts()

InvoiceNo
537434    675
538071    652
538349    620
537638    601
537237    597
         ...
539081      1
536414      1
536405      1
542508      1
542507      1
Name: count, Length: 3339, dtype: int64

In [10]:
# total number of cancelled invoices
n_cancels = dp["InvoiceNo"].astype(str).str.startswith("C").sum()
print(f"\nCancellation rows (InvoiceNo starts with 'C'): {n_cancels:,}")

Cancellation rows (InvoiceNo starts with 'C'): 1,380

In [16]:
#count the quatities whose values are 0 or negative
(dp['Quantity'] <= 0).sum()

np.int64(1511)

In [15]:
#count prices whose values are 0 or negative
(dp['UnitPrice'] <= 0).sum()

np.int64(377)

In [14]:
 # change the dtype of invoice date column
dp["InvoiceDate"] = pd.to_datetime(dp["InvoiceDate"])

In [18]:
# Derived columns
dp["Revenue"]      = dp["Quantity"] * dp["UnitPrice"]
dp["YearMonth"]    = dp["InvoiceDate"].dt.to_period("M")
dp["DayOfWeek"]    = dp["InvoiceDate"].dt.day_name()
dp["Hour"]         = dp["InvoiceDate"].dt.hour
dp["CustomerID"]   = dp["CustomerID"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer